language: go
go:
  - 1.12.x
  - 1.13.x
go_import_path: zgo.at/zhttp
env: ['GO111MODULE=on']
notifications:
  email: false
install:
script: |
  go test -race \
    -coverprofile=coverage.txt \
    -coverpkg=./... \
    ./...
  bash <(curl -s https://codecov.io/bash)
